#Sample Azure CICD Pipeline
trigger:
  - master
pool:
  vmImage: ubuntu-latest
steps:
- bash: |
    set -x
    echo "Welcome to Azure CICD Pipelines"
#- task: Docker@2
#  inputs:
#    containerRegistry: 'myfirstcontainerregistry7'
#    repository: 'helloworldwebapp'
#    command: 'buildAndPush'
#    Dockerfile: '**/Dockerfile'
- script: |
    docker build -t myfirstcontainerregistry7.azurecr.io/helloworldwebapp .
    docker login -u myfirstcontainerregistry7.azurecr.io/helloworldwebapp -p Aravind716@nani myfirstcontainerregistry7.azurecr.io
    docker push myfirstcontainerregistry7.azurecr.io/helloworldwebapp
